package com.cleartsai.mybatis.persistence;

import com.cleartsai.mybatis.model.Pet;
import com.cleartsai.mybatis.model.PetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    int countByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    int deleteByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    List<Pet> selectByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") Pet record, @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    int updateByExample(@Param("record") Pet record, @Param("example") PetExample example);
}