package com.cleartsai.mybatis.model;

import java.util.Date;

public class Pet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.name
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.owner
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.species
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    private String species;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.sex
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.birth
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.death
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    private Date death;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.name
     *
     * @return the value of pet.name
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.name
     *
     * @param name the value for pet.name
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.owner
     *
     * @return the value of pet.owner
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.owner
     *
     * @param owner the value for pet.owner
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.species
     *
     * @return the value of pet.species
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public String getSpecies() {
        return species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.species
     *
     * @param species the value for pet.species
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public void setSpecies(String species) {
        this.species = species == null ? null : species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.sex
     *
     * @return the value of pet.sex
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.sex
     *
     * @param sex the value for pet.sex
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.birth
     *
     * @return the value of pet.birth
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.birth
     *
     * @param birth the value for pet.birth
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.death
     *
     * @return the value of pet.death
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public Date getDeath() {
        return death;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.death
     *
     * @param death the value for pet.death
     *
     * @mbggenerated Sun May 19 11:34:09 CST 2013
     */
    public void setDeath(Date death) {
        this.death = death;
    }
}